// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Context;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AWSDbContext))]
    [Migration("20251019233332_AddFrequency")]
    partial class AddFrequency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Backend.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("カテゴリ名");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("登録日時");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("削除日時");

                    b.Property<int>("IconId")
                        .HasColumnType("int")
                        .HasComment("アイコンID");

                    b.Property<bool>("InoutFlg")
                        .HasColumnType("tinyint(1)")
                        .HasComment("出入金フラグ");

                    b.Property<int>("KakeiboID")
                        .HasColumnType("int")
                        .HasComment("家計簿テーブルID");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新日時");

                    b.HasKey("Id");

                    b.HasIndex("IconId")
                        .IsUnique();

                    b.HasIndex("KakeiboID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Backend.Model.CategoryDefault", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("登録日時");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("削除日時");

                    b.Property<int>("IconId")
                        .HasColumnType("int")
                        .HasComment("アイコンID");

                    b.Property<bool>("InoutFlg")
                        .HasColumnType("tinyint(1)")
                        .HasComment("出入金フラグ");

                    b.Property<string>("KategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("カテゴリ名");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新日時");

                    b.HasKey("Id");

                    b.HasIndex("IconId")
                        .IsUnique();

                    b.ToTable("CategoryDefault");
                });

            modelBuilder.Entity("Backend.Model.Icon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("登録日時");

                    b.Property<string>("DefaultIconName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("表示名");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("削除日時");

                    b.Property<string>("OfficialIconName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("アイコン名");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新日時");

                    b.HasKey("Id");

                    b.ToTable("Icon");
                });

            modelBuilder.Entity("Backend.Model.Kakeibo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("登録日時");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("削除日時");

                    b.Property<string>("KakeiboExplanation")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasComment("説明文");

                    b.Property<string>("KakeiboName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("家計簿名");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新日時");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("ユーザーID");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Kakeibo");
                });

            modelBuilder.Entity("Backend.Model.KakeiboItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasComment("カテゴリID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("登録日時");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("削除日時");

                    b.Property<int>("FrequencyId")
                        .HasColumnType("int")
                        .HasComment("固定費管理ID");

                    b.Property<bool>("InoutFlg")
                        .HasColumnType("tinyint(1)")
                        .HasComment("出入金フラグ");

                    b.Property<int>("ItemAmount")
                        .HasColumnType("int")
                        .HasComment("金額");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("名前");

                    b.Property<int>("KakeiboId")
                        .HasColumnType("int")
                        .HasComment("家計簿テーブルID");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新日時");

                    b.Property<DateTime>("UsedDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("出入金日付");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FrequencyId");

                    b.HasIndex("KakeiboId");

                    b.ToTable("KakeiboItem");
                });

            modelBuilder.Entity("Backend.Model.KakeiboItemFrequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasComment("カテゴリID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("登録日時");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("削除日時");

                    b.Property<DateTime?>("FixedEndDate")
                        .HasMaxLength(20)
                        .HasColumnType("datetime(6)")
                        .HasComment("固定費終了日時");

                    b.Property<DateTime?>("FixedStartDate")
                        .HasMaxLength(20)
                        .HasColumnType("datetime(6)")
                        .HasComment("固定費開始日時");

                    b.Property<int>("Frequency")
                        .HasColumnType("int")
                        .HasComment("固定費頻度");

                    b.Property<bool>("InoutFlg")
                        .HasColumnType("tinyint(1)")
                        .HasComment("出入金フラグ");

                    b.Property<int>("ItemAmount")
                        .HasColumnType("int")
                        .HasComment("金額");

                    b.Property<string>("ItemName")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("名前");

                    b.Property<int>("KakeiboId")
                        .HasColumnType("int")
                        .HasComment("家計簿テーブルID");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新日時");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("KakeiboId");

                    b.ToTable("KakeiboItemFrequency");
                });

            modelBuilder.Entity("Backend.Model.NewsletterTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("登録日時");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("削除日時");

                    b.Property<string>("MailBody")
                        .IsRequired()
                        .HasMaxLength(5120)
                        .HasColumnType("varchar(5120)")
                        .HasComment("メール本文");

                    b.Property<string>("MailTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("メールタイトル");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新日時");

                    b.HasKey("Id");

                    b.ToTable("NewsletterTemplate");
                });

            modelBuilder.Entity("WebApplication.Model.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("登録日時");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("削除日時");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("メールアドレス");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("ユーザー名");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新日時");

                    b.Property<string>("UserHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("ユーザーHash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Model.Category", b =>
                {
                    b.HasOne("Backend.Model.Icon", "Icon")
                        .WithOne("Category")
                        .HasForeignKey("Backend.Model.Category", "IconId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Model.Kakeibo", "Kakeibo")
                        .WithMany("Categories")
                        .HasForeignKey("KakeiboID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icon");

                    b.Navigation("Kakeibo");
                });

            modelBuilder.Entity("Backend.Model.CategoryDefault", b =>
                {
                    b.HasOne("Backend.Model.Icon", "Icon")
                        .WithOne("CategoryDefault")
                        .HasForeignKey("Backend.Model.CategoryDefault", "IconId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("Backend.Model.Kakeibo", b =>
                {
                    b.HasOne("WebApplication.Model.Users", "User")
                        .WithOne("Kakeibo")
                        .HasForeignKey("Backend.Model.Kakeibo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Model.KakeiboItem", b =>
                {
                    b.HasOne("Backend.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Model.KakeiboItemFrequency", "KakeiboItemFrequency")
                        .WithMany("KakeiboItems")
                        .HasForeignKey("FrequencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Model.Kakeibo", "Kakeibo")
                        .WithMany("KakeiboItems")
                        .HasForeignKey("KakeiboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Kakeibo");

                    b.Navigation("KakeiboItemFrequency");
                });

            modelBuilder.Entity("Backend.Model.KakeiboItemFrequency", b =>
                {
                    b.HasOne("Backend.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Model.Kakeibo", "Kakeibo")
                        .WithMany("KakeiboItemFrequencies")
                        .HasForeignKey("KakeiboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Kakeibo");
                });

            modelBuilder.Entity("Backend.Model.Icon", b =>
                {
                    b.Navigation("Category")
                        .IsRequired();

                    b.Navigation("CategoryDefault")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Model.Kakeibo", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("KakeiboItemFrequencies");

                    b.Navigation("KakeiboItems");
                });

            modelBuilder.Entity("Backend.Model.KakeiboItemFrequency", b =>
                {
                    b.Navigation("KakeiboItems");
                });

            modelBuilder.Entity("WebApplication.Model.Users", b =>
                {
                    b.Navigation("Kakeibo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
